In [4]:
!pip install faker

Collecting faker
  Downloading faker-40.15.0-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.15.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 12.8 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.15.0

In [5]:
import pandas as pd
import random
import numpy as np
from faker import Faker

In [6]:
fake = Faker()

In [7]:
num_rows = 1000

# Product Master

In [8]:
categories = {
    "Electronics": ["Mobile", "Laptop", "Tablet", "Accessories"],
    "Clothing": ["Shirts", "Jeans", "Shoes", "Jackets"],
    "Home Appliances": ["Kitchen", "Furniture", "Decor"],
    "Beauty": ["Skincare", "Makeup", "Haircare"],
    "Grocery": ["Snacks", "Beverages", "Essentials"],
    "Sports": ["Fitness", "Outdoor", "Gym Equipment"]
}

brands = [
    "Nike", "Samsung", "Apple", "Sony",
    "Puma", "Adidas", "Nestle", "Loreal",
    "Ikea", "Philips"
]

countries = [
    "India", "China", "USA", "Germany",
    "Vietnam", "Japan", "South Korea"
]

In [9]:
data = []

for i in range(1000):
    category = random.choice(list(categories.keys()))
    sub_category = random.choice(categories[category])

    data.append({
        "product_id": f"P{i+1001}",
        "sku_id": f"SKU{i+5001}",
        "product_name": fake.word().capitalize() + " Product",
        "category": category,
        "sub_category": sub_category,
        "brand": random.choice(brands),
        "launch_date": fake.date_between(
            start_date='-5y',
            end_date='today'
        ),
        "product_status": random.choice(["Active", "Inactive"]),
        "manufacturing_cost": round(
            random.uniform(10, 5000),2
        ),
        "country_of_origin": random.choice(countries)
    })

In [10]:
df_product = pd.DataFrame(data)
df_product.head()

,product_id,sku_id,product_name,category,sub_category,brand,launch_date,product_status,manufacturing_cost,country_of_origin
0,P1001,SKU5001,Baby Product,Grocery,Essentials,Apple,2023-10-25,Active,3676.86,Japan
1,P1002,SKU5002,Guy Product,Home Appliances,Kitchen,Puma,2022-04-19,Inactive,3349.34,USA
2,P1003,SKU5003,Skin Product,Beauty,Haircare,Nestle,2021-12-23,Active,4904.35,Germany
3,P1004,SKU5004,Tax Product,Clothing,Shirts,Nike,2022-03-31,Inactive,1630.68,India
4,P1005,SKU5005,Science Product,Clothing,Shirts,Nestle,2024-09-02,Active,4991.43,USA

In [11]:
df_product.to_csv(
    "product_master.csv",
    index=False
)

# Pricing Data

In [12]:
pricing_data = []

for i, row in df_product.iterrows():

    list_price = round(random.uniform(50, 10000), 2)

    discount_percentage = round(
        random.uniform(0, 30), 2
    )

    final_price = round(
        list_price - (
            list_price * discount_percentage / 100
        ),
        2
    )

    pricing_data.append({
        "pricing_id": f"PR{i+1001}",
        "product_id": row["product_id"],
        "list_price": list_price,
        "discount_percentage": discount_percentage,
        "final_price": final_price,
        "currency": random.choice(
            ["USD", "INR", "AUD"]
        ),
        "effective_date": fake.date_between(
            start_date='-2y',
            end_date='today'
        ),
        "pricing_status": random.choice(
            ["Active", "Expired"]
        )
    })

In [13]:
# Convert to dataframe
df_pricing = pd.DataFrame(pricing_data)

In [14]:
# Preview
print(df_pricing.head())

  pricing_id product_id  list_price  discount_percentage  final_price  \
0     PR1001      P1001     6790.71                16.41      5676.35
1     PR1002      P1002     9258.27                25.16      6928.89
2     PR1003      P1003     1273.54                 2.74      1238.65
3     PR1004      P1004     2474.82                12.39      2168.19
4     PR1005      P1005     7690.65                 5.02      7304.58

  currency effective_date pricing_status
0      AUD     2026-03-10        Expired
1      USD     2026-02-23        Expired
2      INR     2024-09-14         Active
3      USD     2024-05-26         Active
4      USD     2025-09-22         Active

In [15]:
# Row count check
print(df_pricing.shape)

(1000, 8)

In [16]:
# Export CSV
df_pricing.to_csv(
    "pricing_master.csv",
    index=False
)

# Customer Master

In [17]:
num_customers = 5000

customer_data = []

segments = [
    "Retail",
    "Corporate",
    "Premium"
]

loyalty_statuses = [
    "Gold",
    "Silver",
    "Bronze",
    "None"
]

statuses = [
    "Active",
    "Inactive"
]

countries = [
    "India",
    "USA",
    "Australia"
]

for i in range(num_customers):

    customer_data.append({
        "customer_id": f"C{i+1001}",
        "customer_name": fake.name(),
        "email": fake.email(),
        "phone_number": fake.phone_number(),
        "city": fake.city(),
        "state": fake.state(),
        "country": random.choice(countries),
        "signup_date": fake.date_between(
            start_date='-5y',
            end_date='today'
        ),
        "customer_segment": random.choice(segments),
        "loyalty_status": random.choice(loyalty_statuses),
        "customer_status": random.choice(statuses)
    })

## Convert to DataFrame

In [18]:
df_customer = pd.DataFrame(customer_data)

df_customer.head()

,customer_id,customer_name,email,phone_number,city,state,country,signup_date,customer_segment,loyalty_status,customer_status
0,C1001,Rebecca Wallace,burnettjessica@example.net,(397)725-3219,Martinezborough,Louisiana,India,2021-09-20,Premium,Gold,Active
1,C1002,Audrey Richard,travisthomas@example.org,9592344108,New Jamesland,New Mexico,India,2021-08-06,Premium,Bronze,Inactive
2,C1003,Laura Ward,johnfleming@example.net,253.932.5597,East Colleen,Utah,USA,2022-07-22,Corporate,None,Inactive
3,C1004,Sandra Nelson,smithcarmen@example.net,586.889.3515,Thomasburgh,New Jersey,Australia,2024-11-27,Retail,Bronze,Inactive
4,C1005,Anthony Johnson,marc23@example.com,001-222-281-0787x10967,Lake Jessicaborough,Kansas,Australia,2025-03-08,Retail,None,Inactive

In [19]:
# Validate rows
df_customer.shape

(5000, 11)

In [20]:
# Export to CSV
df_customer.to_csv(
    "customer_master.csv",
    index=False
)

# Order Transaction

In [21]:
df_product = pd.read_csv("product_master.csv")
df_pricing = pd.read_csv("pricing_master.csv")
df_customer = pd.read_csv("customer_master.csv")

## Create helper lists

In [22]:
product_ids = df_product["product_id"].tolist()
customer_ids = df_customer["customer_id"].tolist()

pricing_dict = dict(
    zip(
        df_pricing["product_id"],
        df_pricing["final_price"]
    )
)

In [23]:
# Generate Orders Data
num_orders = 100000

order_data = []

order_statuses = [
    "Delivered",
    "Cancelled",
    "Returned",
    "In Transit"
]

payment_methods = [
    "Credit Card",
    "UPI",
    "Debit Card",
    "PayPal"
]

for i in range(num_orders):

    product_id = random.choice(product_ids)
    customer_id = random.choice(customer_ids)

    quantity = random.randint(1, 5)

    unit_price = pricing_dict[product_id]

    total_order_amount = round(
        quantity * unit_price,
        2
    )

    order_data.append({
        "order_id": f"O{i+1001}",
        "customer_id": customer_id,
        "product_id": product_id,
        "order_date": fake.date_between(
            start_date='-3y',
            end_date='today'
        ),
        "quantity": quantity,
        "unit_price": unit_price,
        "total_order_amount": total_order_amount,
        "order_status": random.choice(order_statuses),
        "payment_method": random.choice(payment_methods),
        "shipping_city": fake.city(),
        "shipping_country": random.choice(
            ["India", "USA", "Australia"]
        )
    })

In [24]:
# Convert to DataFrame
df_orders = pd.DataFrame(order_data)

df_orders.head()

,order_id,customer_id,product_id,order_date,quantity,unit_price,total_order_amount,order_status,payment_method,shipping_city,shipping_country
0,O1001,C1792,P1226,2025-05-09,3,4127.40,12382.20,In Transit,PayPal,Sherrymouth,Australia
1,O1002,C5596,P1952,2025-07-15,4,1236.52,4946.08,Returned,Debit Card,Burnettview,Australia
2,O1003,C2330,P1109,2025-04-01,1,2932.58,2932.58,In Transit,UPI,New Craig,Australia
3,O1004,C3484,P1949,2024-06-12,3,2967.81,8903.43,Cancelled,Debit Card,East Brendastad,India
4,O1005,C3292,P1129,2023-08-19,5,1956.80,9784.00,Cancelled,UPI,West Heatherport,India

In [25]:
# Validate row count
df_orders.shape

(100000, 11)

In [26]:
# Export CSV
df_orders.to_csv(
    "orders_transactions.csv",
    index=False
)

# Revenue Transaction

In [27]:
# Generate Revenue Dataset
revenue_data = []

payment_statuses = [
    "Completed",
    "Pending",
    "Failed",
    "Refunded"
]

finance_systems = [
    "Stripe",
    "PayPal",
    "Bank Transfer",
    "Internal Finance System"
]

for i, row in df_orders.iterrows():

    gross_revenue = row["total_order_amount"]

    tax_amount = round(
        gross_revenue * random.uniform(0.05, 0.18),
        2
    )

    refund_amount = round(
        gross_revenue * random.uniform(0, 0.20),
        2
    ) if row["order_status"] == "Returned" else 0

    net_revenue = round(
        gross_revenue + tax_amount - refund_amount,
        2
    )

    revenue_data.append({
        "revenue_id": f"R{i+1001}",
        "order_id": row["order_id"],
        "gross_revenue": gross_revenue,
        "tax_amount": tax_amount,
        "refund_amount": refund_amount,
        "net_revenue": net_revenue,
        "transaction_date": row["order_date"],
        "payment_status": random.choice(payment_statuses),
        "finance_system": random.choice(finance_systems)
    })

In [28]:
# Convert to DataFrame
df_revenue = pd.DataFrame(revenue_data)

df_revenue.head()

,revenue_id,order_id,gross_revenue,tax_amount,refund_amount,net_revenue,transaction_date,payment_status,finance_system
0,R1001,O1001,12382.20,1975.06,0.00,14357.26,2025-05-09,Refunded,PayPal
1,R1002,O1002,4946.08,533.17,510.16,4969.09,2025-07-15,Pending,Internal Finance System
2,R1003,O1003,2932.58,449.13,0.00,3381.71,2025-04-01,Failed,PayPal
3,R1004,O1004,8903.43,1590.15,0.00,10493.58,2024-06-12,Failed,Internal Finance System
4,R1005,O1005,9784.00,999.10,0.00,10783.10,2023-08-19,Completed,Internal Finance System

In [29]:
# Validate row count
df_revenue.shape

(100000, 9)

In [30]:
# Export CSV
df_revenue.to_csv(
    "revenue_transactions.csv",
    index=False
)

# Historical Transaction

In [31]:
# Create helper lists
product_ids = df_product["product_id"].tolist()
customer_ids = df_customer["customer_id"].tolist()

pricing_dict = dict(
    zip(
        df_pricing["product_id"],
        df_pricing["final_price"]
    )
)

In [32]:
# Generate Historical Dataset
num_transactions = 300000

historical_data = []

channels = [
    "Online",
    "Retail Store",
    "Mobile App"
]

statuses = [
    "Completed",
    "Returned",
    "Cancelled"
]

regions = [
    "North America",
    "Asia Pacific",
    "Europe"
]

for i in range(num_transactions):

    product_id = random.choice(product_ids)
    customer_id = random.choice(customer_ids)

    quantity = random.randint(1, 5)

    sales_amount = round(
        quantity * pricing_dict[product_id],
        2
    )

    historical_data.append({
        "transaction_id": f"H{i+1001}",
        "customer_id": customer_id,
        "product_id": product_id,
        "transaction_date": fake.date_between(
            start_date='-7y',
            end_date='-3y'
        ),
        "quantity": quantity,
        "sales_amount": sales_amount,
        "transaction_channel": random.choice(channels),
        "region": random.choice(regions),
        "transaction_status": random.choice(statuses)
    })

In [33]:
# Convert to DataFrame
df_historical = pd.DataFrame(historical_data)

df_historical.head()

,transaction_id,customer_id,product_id,transaction_date,quantity,sales_amount,transaction_channel,region,transaction_status
0,H1001,C5347,P1757,2020-03-02,4,8543.20,Mobile App,North America,Returned
1,H1002,C5168,P1205,2021-01-10,4,4403.20,Retail Store,Asia Pacific,Returned
2,H1003,C1129,P1045,2022-04-09,5,20074.70,Mobile App,North America,Cancelled
3,H1004,C3105,P1142,2022-05-03,5,7168.10,Mobile App,Europe,Cancelled
4,H1005,C2198,P1986,2021-02-27,1,640.23,Mobile App,Asia Pacific,Cancelled

In [34]:
# Validate row count
df_historical.shape

(300000, 9)

In [35]:
# Export CSV
df_historical.to_csv(
    "historical_transactions.csv",
    index=False
)